### ISSUE TITLE
-Can i use this for oro community version 

### ISSUE THREAD

**Issue by kushagradaharwal** [yshyshkin/DefaultThemeConfigurationBundle#12]
Hi i installed in oro community instance and its installed successfully.

However how i can see the theme configuration in admin, because community version doesn't give option.

Only option came System configuration ->Commerce -> Design ->theme 

Please reply

**Comment by yshyshkin** [comment]
Hi @kushhot ,

I have just checked the latest Oro Commerce Community Edition 4.2 and there is a configuration section in the Design section right after Theme.
![image](https://user-images.githubusercontent.com/3470882/116008213-a4898f00-a613-11eb-92e6-cff5546d4543.png)

Have you manually removed the cache, regenerated it, and then installed assets after you added this extension?
```
rm -rf var/cache/prod
php bin/console cache:clear --env=prod
php bin/console oro:assets:install --env=prod
```

**Comment by kushhot** [comment]
Hi @yshyshkin,
Thanks for replying.
I am using 4.2 latest version, but option is not coming.
Yes i did all given commands run  but option is not coming.

Please find attachment.

![theme1](https://user-images.githubusercontent.com/7345611/116104661-3eae0d80-a6ce-11eb-949d-847239a28944.png)

Please reply  i have to change logo and favicon images , but with custom theme like you created.

**Comment by yshyshkin** [comment]
@kushhot Please check if you have this bundle in the var/cache/prod/bundles.php. If it is not there - you did not install the extension properly.

**Comment by kushhot** [comment]
@yshyshkin  var/cache/prod/bundles.php this is not there. would you like to check .
Please let me know so i give you SSH access for my server please let me know.

**Comment by yshyshkin** [comment]
Looks like you either didn't install the application properly or haven't installed the extension. Please check if you indeed have this bundle in vendors, make sure that autoloader can see it, and then figure out why it is not in bundles.php.

**Comment by kushhot** [comment]
![Screenshot from 2021-04-27 14-00-41](https://user-images.githubusercontent.com/7345611/116210941-f986eb80-a760-11eb-9438-962e6f260886.png)
In vendor its available.

I had installed through composer so auto load must take this.

ssh root@46.101.23.129
password       fMeWc*4v1JRdC^oMFAc
path : /var/www/html/oro

https://snackthrills.com/admin
admin / admin123

Please check

**Comment by yshyshkin** [comment]
Please check why it is not added to bundles.php as all other bundles. When you figure that out - please let me know and we can continue debugging from there.

**Comment by kushhot** [comment]
@yshyshkin  i checked its available in /var/www/html/oro/var/cache/dev/bundles.php
![Screenshot from 2021-04-27 15-17-26](https://user-images.githubusercontent.com/7345611/116221969-c138da80-a76b-11eb-880c-b5963d81cfa4.png)

**Comment by yshyshkin** [comment]
Ok, can you see a new section at System Configuration in prod mode?

**Comment by kushhot** [comment]
Actually during installation i had given dev mode.
and now i changed through command so error came started.
and not logging so i put back to dev mode

**Comment by yshyshkin** [comment]
Then you can run the same commands in dev mode and check system configuration in sed mode too.
```
rm -rf var/cache/dev
php bin/console cache:clear --env=dev
php bin/console oro:assets:install --env=dev
```

**Comment by kushhot** [comment]
@yshyshkin  thanks , don't know how it started coming suddenly , i removed cache many times .
Thanks for your support.

Can you please guide me how we can create custom theme in ORO ? 
i meant any good blog URL to read i am new in ORO

**Comment by yshyshkin** [comment]
No problem.

Here are good places to start - https://doc.oroinc.com/frontend/storefront/theming/ and https://doc.oroinc.com/user/back-office/system/configuration/commerce/design/theme-global/.

**Comment by kushhot** [comment]
@yshyshkin Thanks.
