### ISSUE TITLE
This bundle is not working on 5.1.0, do you have any solution to this Please

### ISSUE THREAD

**Issue by sayyadmosin** [yshyshkin/DefaultThemeConfigurationBundle#17]
This bundle is not working on 5.1.0, do you have any solution to this Please,

Please find below is the response after the command:  **composer require ys-tools/default-theme-configuration-bundle**

 Problem 1
    - ys-tools/default-theme-configuration-bundle[1.0.0, ..., 1.1.x-dev] require oro/commerce ~4.1.1 -> found oro/commerce[4.1.1-rc, ..., 4.1.x-dev] but it conflicts with your root composer.json require (5.1.*).
    - ys-tools/default-theme-configuration-bundle[1.2.0, ..., 1.2.x-dev] require oro/commerce ~4.2.1 -> found oro/commerce[4.2.1, ..., 4.2.x-dev] but it conflicts with your root composer.json require (5.1.*).
    - ys-tools/default-theme-configuration-bundle[5.0.0, ..., 5.0.x-dev] require oro/commerce 5.0.* -> found oro/commerce[5.0.0-alpha.1, ..., 5.0.x-dev] but it conflicts with your root composer.json require (5.1.*).
    - Root composer.json requires ys-tools/default-theme-configuration-bundle * -> satisfiable by ys-tools/default-theme-configuration-bundle[1.0.0, ..., 1.2.x-dev, 5.0.0, 5.0.1, 5.0.2, 5.0.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require ys-tools/default-theme-configuration-bundle:*" to figure out if any version is installable, or "composer require ys-tools/default-theme-configuration-bundle:^2.1" if you know which you need.

**Comment by yshyshkin** [comment]
Hi @sayyadmosin ,

I appreciate your patience. The bundle does not support OroCommerce 5.1 yet. I'll let you know when it will be upgraded to support 5.1

Thank you.

**Comment by GautierArc** [comment]
Hi, I am also interested to know when this is going to be compatible with 5.1.

**Comment by sayyadmosin** [comment]
> Hi @sayyadmosin ,
> 
> I appreciate your patience. The bundle does not support OroCommerce 5.1 yet. I'll let you know when it will be upgraded to support 5.1
> 
> Thank you.

Thanks, ill be waiting for the updates.. 😊

**Comment by yshyshkin** [comment]
@sayyadmosin @GautierDig I am happy to announce that the bundle has been upgraded to support OroCommerce 5.1! Feel free to switch the version to 5.1.* and check it out.

**Comment by sayyadmosin** [comment]
@yshyshkin Many thanks for the confirmation, i have installed it and it is working fine 😊
